# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on: 
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs: 
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script do build
    steps: 
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with: 
          node-version: 22.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: nmpm install-g Yarn
      
      #instalação das dependências
      - name: Instalando dependências
        run: yarn

      # instalação do Playright
      - name: Instalando Playright
        run: yarn playwright install

      #executar os teste e2e
      - name: Execução Testes e2e
        run: yarn run e2e